export const sampleProperty = {
  // Basic Information
  property_reference: "noble-remix-772-621",
  building_name: "Noble Remix",
  unit_number: "772/621",
  full_address: "772 Sukhumvit Rd, Khlong Tan, Khlong Toei, Bangkok 10110",
  property_type: "Luxury Condo",
  square_meters: 68,
  bedrooms: 1,
  bathrooms: 1,
  max_occupancy: 3,
  primary_photo: "/placeholder.svg?height=300&width=400&query=luxury condo interior",
  floor_plan: "/placeholder.svg?height=600&width=800&query=floor plan",
  year_built: "2019",
  year_renovated: "2023",
  description:
    "Modern one-bedroom luxury condo in the heart of Sukhumvit with city views, high-end furnishings, and full amenities.",

  // Safety & Security
  smoke_detectors: ["Living Room", "Kitchen", "Hallway"],
  fire_extinguisher_location: "Kitchen cabinet under sink (expires 12/2026)",
  fire_extinguisher_expiry: "2026-12-31",
  emergency_exit_plan: true,
  first_aid_location: "Bathroom cabinet",
  door_lock_type: "Digital Smart Lock",
  smart_lock_code: "230597#",
  building_security: "24/7 Security Guards, CCTV, Key Card Access",
  cctv_coverage: ["Building Entrance", "Elevator", "Hallways", "Parking"],
  emergency_contacts: "Building Manager: +66 81 234 5678\nEmergency: 191\nTourist Police: 1155",
  window_security: "Safety locks on all windows",
  balcony_safety: "Glass barriers 1.2m high, no child hazards",
  child_safety_features: ["Socket covers", "Cabinet locks", "No sharp edges"],

  // Kitchen & Dining
  major_appliances: [
    "Samsung Smart Refrigerator",
    "Electrolux Induction Cooktop",
    "Teka Built-in Oven",
    "Teka Dishwasher",
  ],
  small_appliances: ["Nespresso Coffee Machine", "Electric Kettle", "Toaster", "Rice Cooker", "Blender"],
  cookware_inventory: "Complete set of stainless steel pots and pans (10 pieces)",
  dishware_count: "Service for 4 (16 pieces including plates, bowls, mugs, glasses)",
  dining_capacity: 4,
  water_filtration: "Under-sink 3-stage filtration system",
  coffee_tea_facilities: "Nespresso with starter pods, electric kettle, tea selection",
  special_features: "Marble countertops, ambient lighting, pull-out pantry",
  waste_disposal: "Separate bins for general waste and recycling under sink",
  pantry_staples: ["Salt", "Pepper", "Cooking oil", "Basic spices", "Tea", "Coffee"],
  counter_material: "Premium white marble",
  kitchen_photos: ["/placeholder.svg?height=300&width=400&query=luxury kitchen"],

  // Bedrooms
  bed_configurations: ["King size (180x200cm)"],
  extra_bedding_location: "Closet top shelf",
  mattress_type: "Luxury pocket spring, medium firm",
  pillow_details: "4 sleeping pillows, 2 decorative pillows",
  closet_details: "Walk-in closet with 10 hangers, 4 drawers, and shoe rack",
  blackout_curtains: true,
  bedroom_electronics: ["Smart TV", "Bluetooth speaker", "Alarm clock with USB charging"],
  furniture_inventory: "Bed, 2 nightstands, dresser, chair, full-length mirror",
  bedroom_amenities: ["Reading lamp", "Full-length mirror", "Workspace desk"],

  // Bathrooms
  shower_bath_config: "Walk-in rainfall shower",
  towel_details: "4 bath, 4 hand, 2 face (luxury cotton)",
  toiletries_provided: ["Shampoo", "Conditioner", "Body wash", "Soap", "Hand soap", "Lotion"],
  hair_dryer_available: true,
  hair_dryer_details: "1800W professional",
  water_pressure: "Excellent",
  hot_water_system: "Tankless water heater",
  ventilation: "Exhaust fan with humidity sensor",
  bathroom_special_features: ["Heated floors", "Magnifying mirror", "Rain shower head"],
  bathroom_accessibility_features: ["Grab bars", "Non-slip surfaces"],

  // Technology
  wifi_network: "Noble_Remix_772",
  wifi_password: "NR772BKK2023!",
  internet_speed: "1 Gbps fiber optic",
  smart_home_features: ["Google Home Hub", "Smart lighting", "Smart curtains", "Smart AC control"],
  router_location: "Cabinet in living room",
  tv_details: '55" Samsung QLED Smart TV with Netflix, Disney+, YouTube access',
  streaming_services: "Netflix, Disney+, YouTube Premium",
  speaker_systems: "Sonos sound system in living room",
  remote_controls: ["TV remote", "AC remote", "Sonos remote", "Google Home remote"],
  charging_stations: "USB charging ports by bed and in living room",
  backup_solutions: "Portable WiFi hotspot in drawer if main internet fails",

  // Practical Living
  washer_details: "LG Front-load, Quick wash: 30 mins, Normal: 1 hour",
  dryer_details: "LG Heat pump dryer, Eco mode recommended",
  detergent_provided: true,
  iron_board_available: true,
  drying_rack_location: "Foldable rack on balcony",
  laundry_basket_available: "Rattan basket in bathroom",
  building_laundry_info: "N/A - In-unit laundry",
  vacuum_details: "Dyson cordless in utility closet",
  cleaning_supplies: ["All-purpose cleaner", "Glass cleaner", "Disinfectant wipes", "Floor cleaner"],
  cleaning_schedule: "Weekly cleaning service (Mondays 10am)",
  special_instructions: "Marble counters need special cleaner (provided under sink)",
  stain_removal_kit: true,
  ac_units_details: "2 Daikin units (living room, bedroom) with individual remotes",
  heating_system: "AC units with heat function",
  thermostat_instructions: "Nest thermostat with automated schedule",
  ventilation_systems: "Central system plus bathroom fans",
  air_purifiers: "Dyson in bedroom, replacement filters in closet",
  electrical_panel_location: "Behind decorative panel in entryway",

  // Location & Lifestyle
  public_transport: "BTS Thong Lo Station (350m, 5min walk)",
  nearby_locations: ["EmQuartier Mall (1.2km)", "Benjasiri Park (800m)", "Sukhumvit Soi 55 (Thonglor)"],
  walking_score: 92,
  neighborhood_description: "Upscale expat area with dining, shopping",
  restaurants: ["Soul Food", "Supanniga", "Roast", "Seed"],
  grocery_shopping: "Villa Market (200m), Foodland (500m)",
  tourist_attractions: ["EmQuartier", "Benchakitti Park", "Thonglor nightlife"],
  emergency_services: "Samitivej Hospital (1.2km), Police (800m)",
  local_tips: "Tuesday street food market on Soi 38",
  weather_patterns: "Rainy season May-Oct, peak heat March-April",
  safety_assessment: "Very Safe",

  // Accessibility & Sustainability
  step_free_access: "Complete step-free access throughout",
  elevator_accessibility: "1.5m x 1.8m, wheelchair accessible",
  doorway_widths: "All doorways 90cm+ width",
  bathroom_features: ["Roll-in shower", "Grab bars"],
  kitchen_height: "Counter height 85cm, sink accessible",
  visual_features: ["High contrast switches"],
  auditory_features: ["Visual doorbell"],
  energy_rating: "A+ (Highest efficiency)",
  renewable_features: "Building has solar panels for common areas",
  recycling_instructions: "Separate bins for plastic, paper, glass",
  efficient_appliances: ["Energy Star refrigerator", "LED lighting"],
  water_conservation: ["Low-flow fixtures", "Dual-flush toilet"],
  eco_products: ["Organic toiletries", "Eco cleaning supplies"],
  sustainable_materials: "Bamboo flooring, Recycled glass counters",
}
